privoda/Controllers/TeSysConfiguratorController.cs
using Microsoft.AspNetCore.Mvc;
using privoda.Contracts.Repositories;
using privoda.Contracts.Services;
using privoda.Models;
using privoda.Services;
using privoda.Utils.ReCaptchaV2;
using privoda.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace privoda.Controllers
{
    public class TeSysConfiguratorController : Controller
    {
        private readonly IService<PowerAndCurrent> _powerAndCurrentService;
        private readonly IService<CurrentType> _currentTypeService;
        private readonly IService<CircuitBreaker> _circuitBreakerService;
        private readonly IService<Contactor> _contactorService;
        private readonly IService<Coil> _coilService;
        private readonly ICoilRepository _coilRepository;
        private readonly TeSysService _teSysService;
        private readonly EmailService _emailService;

        public TeSysConfiguratorController(IService<PowerAndCurrent> powerAndCurrentService, IService<CurrentType> currentTypeService, 
            ICoilRepository coilRepository, IService<CircuitBreaker> circuitBreakerService, IService<Contactor> contactorService,
            IService<Coil> coilService, TeSysService teSysService, EmailService emailService)
        {
            _powerAndCurrentService = powerAndCurrentService;
            _currentTypeService = currentTypeService;
            _coilRepository = coilRepository;
            _circuitBreakerService = circuitBreakerService;
            _contactorService = contactorService;
            _coilService = coilService;
            _teSysService = teSysService;
            _emailService = emailService;
        }

        public async Task<IActionResult> Index()
        {
            TeSysConfiguratorViewModel teSysConfiguratorViewModel = new TeSysConfiguratorViewModel()
            {
                PowerAndCurrentList = await _powerAndCurrentService.GetManyAsync(),
                CurrentTypes = await _currentTypeService.GetManyAsync(),
                VoltageList = await _coilRepository.GetAllVoltage()
            };
            return View(teSysConfiguratorViewModel);
        }

        public async Task<IActionResult> Configurate(ConfigurateFirstTypeViewModel configurateFirstTypeViewModel)
        {
            TeSysConfiguratorViewModel teSysConfiguratorViewModel = new TeSysConfiguratorViewModel()
            {
                PowerAndCurrentList = await _powerAndCurrentService.GetManyAsync(),
                CurrentTypes = await _currentTypeService.GetManyAsync(),
                VoltageList = await _coilRepository.GetAllVoltage(),
                TeSysType1 = await _teSysService.GetFirstTypeAsync(configurateFirstTypeViewModel.Current,
                configurateFirstTypeViewModel.Voltage, configurateFirstTypeViewModel.CurrentType),
                TeSysType2 = await _teSysService.GetSecondTypeAsync(configurateFirstTypeViewModel.Current,
                configurateFirstTypeViewModel.Voltage, configurateFirstTypeViewModel.CurrentType)
            };
            return View("Index", teSysConfiguratorViewModel);
        }

        public async Task<IActionResult> SendConfigurationRefs(string email, string phone, 
            string teSys1FullRef, string teSys1CircuitBreakersRef, string teSys1CoilRef, string teSys1ContactorRef, 
            string teSys2FullRef, string teSys2CircuitBreakersRef, string teSys2CoilRef, string teSys2ContactorRef)
        {
            string captchaResponse = HttpContext.Request.Form["g-Recaptcha-Response"];
            ReCaptchaValidationResult result = ReCaptchaValidator.IsValid(captchaResponse);
            if (!result.Success)
            {
                return RedirectToAction("Index");
            }
            _emailService.SendConfigurationRefs(email,phone,
            teSys1FullRef, teSys1CircuitBreakersRef, teSys1CoilRef, teSys1ContactorRef,
            teSys2FullRef, teSys2CircuitBreakersRef, teSys2CoilRef, teSys2ContactorRef);
            return RedirectToAction("Success");
        }

        public IActionResult Success()
        {
            return View();
        }
    }
}

privoda/Views/Shared/Success.cshtml
@{
    ViewData["Title"] = "Успешный запрос";
}

<body>
    <div class="container">
        <div class="text-center">
            <img class="success-img" src="~/images/success.png" />
        </div>
        <h2>Запрос комерческого предложения оформлен успешно!</h2>
        <p>
            Спасибо за оформление комерческого предложения на privoda.by<br />
            Через некоторое время с вами свяжутся наши специалисты.
        </p>
        <a asp-controller="Home" asp-action="Index" class="btn btn-default">На главную</a>
    </div>
</body>

privoda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/mystyles.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-left"><img src="~/images/logo1.png" style="height: 35px; margin-top: 10px;"/></a>
                <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="navbar-collapse collapse navHeaderCollapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Главная</a></li>
                    <li><a asp-controller="TeSysConfigurator" asp-action="Index">Конфигуратор пускателей</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Lines">Преобразователи частоты</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Library">Библиотека</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="fixed-button"><a href="#selectModal" data-toggle="modal">Подобрать решение</a></div>
    <!-- Modal -->
    <div id="selectModal" class="popup-form modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <div style="text-align: left">Подбор решения</div>
                </div>
                <div class="modal-body">

                    <form role="form" asp-area="" asp-controller="Home" asp-action="Select">
                        <div class="form-group">
                            <label for="normal">Рабочий режим</label>
                            <p>Нормальный</p>
                            <select class="form-control" name="normal" id="normal" onchange="dropHardSelectFunction()">
                                <option value="" selected>-- Выберите --</option>
                                <option>Центробежный насос (время пуска 5-15сек)</option>
                                <option>Поршневой насос (время пуска 5-10сек)</option>
                                <option>Вентилятор (время пуска 10-30сек)</option>
                                <option>Холодильный компрессор</option>
                                <option>Винтовой компрессор</option>
                                <option>Центробежный компрессор (время пуска 10-30сек)</option>
                                <option>Поршневой компрессор</option>
                                <option>Конвейер, транспортер</option>
                                <option>Винтовой домкрат</option>
                                <option>Подъемник</option>
                                <option>Элеватор</option>
                                <option>Круговая, ленточная пила (время пуска 10-30сек)</option>
                                <option>Мешалка</option>
                                <option>Смеситель</option>
                                <option>Рафинер</option>
                            </select>
                            <br />
                            <p>Тяжёлый</p>
                            <select class="form-control" name="hard" id="hard" onchange="dropNormalSelectFunction()">
                                <option value="" selected>-- Выберите --</option>
                                <option>Вентилятор (время пуска 30-40сек)</option>
                                <option>Центробежный компрессор (время пуска 30-40сек)</option>
                                <option>Круговая, ленточная пила (время пуска 30-60сек)</option>
                                <option>Протирочная машина, мясоразделочный нож</option>
                                <option>Мельница</option>
                                <option>Дробилка</option>
                                <option>Пресс</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="inputOrganization">Циклограмма работы</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="workSequences" id="workSequence1" value="Повторно-кратковременный">
                                <label class="form-check-label" for="exampleRadios1">
                                    Повторно-кратковременный
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="workSequences" id="workSequence2" value="Длительный">
                                <label class="form-check-label" for="exampleRadios2">
                                    Длительный
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputOrganization">Напряжение питания</label>
                            <select class="form-control" name="inputOrganization" required>
                                <option>Однофазная 100-120 В</option>
                                <option>Однофазная 200-240 В</option>
                                <option>Трёхфазная 200-230 В</option>
                                <option>Трёхфазная 200-240 В</option>
                                <option>Трёхфазная 380-480 В</option>
                                <option>Трёхфазная 380-500 В</option>
                                <option>Трёхфазная 525-600 В</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="inputStatus">Параметры двигателя</label>
                            <p>Мощность [кВт]</p>
                            <input class="form-control" name="power" id="power" required />
                            <p>Ток в обмотке[А]</p>
                            <input class="form-control" name="current" id="current" required />
                            <p>Скорость вращения[об/мин]</p>
                            <input class="form-control" name="speed" id="speed" />
                            <p>Cos(f)</p>
                            <input class="form-control" name="cos" id="cos" />
                        </div>
                        <div class="form-group">
                            <label for="problem">Описание проблемы</label>
                            <textarea class="form-control" name="problem" rows="3"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="inputStatus">E-mail</label>
                            <input type="email" class="form-control" id="inputStatus" name="email" placeholder="Введите контактный адресс эл. почты" required />
                        </div>
                        <div class="g-recaptcha"
                             data-callback="recaptchaCallback"
                             data-sitekey="6Lde1r4UAAAAALjc45fRCMTWcQd7euopVl0KSxfU">
                        </div>
                        <div class="text-right">
                            <button id="submitBtn" type="submit" class="btn btn-default" disabled>Отправить</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

    <div class="body-content">
        @RenderBody()
    </div>
    <footer>
        <hr />
        <div class="container">
            <br />
            <p>Контактная информация:</p>
            <p>
                Отдел продаж: 8(029)642-06-37<br />
                Технический отдел: 8(044)531-65-30<br />
                Почта отдела продаж: info@profes.by<br />
                Почта технического отдела: service@profes.by
            </p>
            <br />
            <br />
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</body>
</html>